# Generated by Django 4.0.1 on 2022-02-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0003_alter_question_a1_alter_question_a2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remember.patient', unique=True),
        ),
    ]
