# Generated by Django 4.0.1 on 2022-03-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0004_alter_quiz_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a4',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='patient',
            name='lastName',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='timeEnded',
            field=models.DateTimeField(default=datetime.date(2022, 2, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='Temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.FileField(default='', max_length=200, upload_to='uploads/images/question_pics/'),
        ),
    ]
