# Generated by Django 4.0.1 on 2022-03-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0004_alter_quiz_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='a4',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='patient',
            name='lastName',
            field=models.CharField(default='hello world', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mugshot',
            field=models.FileField(default='', max_length=200, upload_to='uploads/images/patient_pics/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='hello world', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.FileField(default='', max_length=200, upload_to='uploads/images/question_pics/'),
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='QuizResult',
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remember.question')),
                ('quizResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remember.quizresult')),
            ],
        ),
    ]
