# Generated by Django 4.0.1 on 2022-03-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0005_rename_name_patient_firstname_rename_a1_question_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remember.patient'),
        ),
    ]
