# Generated by Django 4.0.1 on 2022-03-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0006_alter_quiz_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mugshot',
            field=models.FileField(default='', max_length=200, upload_to='uploads/images/patient_pics/'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Remember.user'),
            preserve_default=False,
        ),
    ]
