# Generated by Django 4.0.1 on 2022-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0007_patient_mugshot_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mugshot',
            field=models.FileField(default='', max_length=200, upload_to='./Remember/static/remember/images/patientMugShots/'),
        ),
    ]
