# Generated by Django 4.0.1 on 2022-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remember', '0008_alter_patient_mugshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.BinaryField(max_length=200),
        ),
    ]
